# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewTaskWidgetGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TaskWidgetGUI(object):
    def setupUi(self, Form):
        # Form.resize(436, 147)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 670, 131))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.subject_edit = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.subject_edit.setFont(font)
        self.subject_edit.setObjectName("subject_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.subject_edit)
        self.type_edit = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.type_edit.setFont(font)
        self.type_edit.setObjectName("type_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.type_edit)
        self.name_edit = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name_edit.setFont(font)
        self.name_edit.setObjectName("name_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.name_edit)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.count_edit = QtWidgets.QSpinBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.count_edit.setFont(font)
        self.count_edit.setMinimum(1)
        self.count_edit.setProperty("value", 1)
        self.count_edit.setObjectName("count_edit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.count_edit)
        self.view_button = QtWidgets.QPushButton(Form)
        self.view_button.setGeometry(QtCore.QRect(700, 40, 25, 25))
        self.view_button.setText("")
        self.view_button.setObjectName("view_button")
        self.delete_button = QtWidgets.QPushButton(Form)
        self.delete_button.setGeometry(QtCore.QRect(700, 10, 25, 25))
        self.delete_button.setText("")
        self.delete_button.setObjectName("delete_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        # Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Предмет"))
        self.label_2.setText(_translate("Form", "Тип"))
        self.label_3.setText(_translate("Form", "Название"))
        self.label_4.setText(_translate("Form", "Количество"))
